# filename: docker-compose.yml
services:
  svr_n8n:
    build: .
    image: n8n-custom-ffmpeg
    container_name: n8n_container
    user: "1000:1000"
    environment:
      - NODE_OPTIONS=--max_old_space_size=4096
      - N8N_SECURE_COOKIE=false
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
      - N8N_PORT=5678
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
      # Optional: set a consistent user folder, but you already mount /home/node/.n8n
      # - N8N_USER_FOLDER=/home/node/.n8n
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data:/home/node/.n8n
      - /tmp:/tmp
